apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
   annotations:
     argocd.argoproj.io/sync-wave: "2"
   labels:
     machineconfiguration.openshift.io/role: worker
   name: 18-worke-motd
spec:
   config:
     ignition:
       version: 3.2.0
     storage:
       files:
       - contents:
           source: data:text/plain;base64,KioqIGhlbGxvLCBtb3RkICoqKgo=
         filesystem: root
         mode: 420
         path: /etc/motd
