apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "3"
  name: postsync-job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          echo "*** PostSync is called ***"
        image: registry.redhat.io/ose-cli:v4.14
        name: postsync-job
        resources: {}
      restartPolicy: Never
status: {}
